package cmd

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"strings"

	"github.com/spf13/cobra"
)

var hooksCmd = &cobra.Command{
	Use:   "hooks",
	Short: "Manage Git hooks integration",
	Long:  `Install, uninstall, or list Git hooks for automatic commit message generation.`,
}

var installHookCmd = &cobra.Command{
	Use:   "install",
	Short: "Install Git hooks",
	Long: `Install prepare-commit-msg hook to automatically generate commit messages.
The hook will run cgpd when no commit message is provided.`,
	RunE: installHooks,
}

var uninstallHookCmd = &cobra.Command{
	Use:   "uninstall",
	Short: "Uninstall Git hooks",
	Long:  `Remove the installed prepare-commit-msg hook.`,
	RunE:  uninstallHooks,
}

var listHookCmd = &cobra.Command{
	Use:   "list",
	Short: "List installed hooks",
	Long:  `Show the status of cgpd Git hooks.`,
	RunE:  listHooks,
}

func init() {
	rootCmd.AddCommand(hooksCmd)
	hooksCmd.AddCommand(installHookCmd)
	hooksCmd.AddCommand(uninstallHookCmd)
	hooksCmd.AddCommand(listHookCmd)
}

func getGitRoot() (string, error) {
	cmd := exec.Command("git", "rev-parse", "--git-dir")
	out, err := cmd.Output()
	if err != nil {
		return "", errors.New("not a git repository")
	}
	gitDir := strings.TrimSpace(string(out))
	if !filepath.IsAbs(gitDir) {
		wd, err := os.Getwd()
		if err != nil {
			return "", err
		}
		gitDir = filepath.Join(wd, gitDir)
	}
	return gitDir, nil
}

func getCgpdPath() (string, error) {
	// Try to find cgpd in PATH
	path, err := exec.LookPath("cgpd")
	if err == nil {
		return path, nil
	}

	// Fallback to current executable
	exe, err := os.Executable()
	if err != nil {
		return "", fmt.Errorf("cannot determine cgpd location: %w", err)
	}
	return exe, nil
}

func generateHookScript(cgpdPath string) string {
	// For Windows, use .exe extension
	if runtime.GOOS == "windows" {
		return fmt.Sprintf(`#!/bin/sh
# Auto-generated by cgpd
# This hook automatically generates commit messages using cgpd

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2

# Only run if no commit message provided (not amend, merge, etc.)
if [ -z "$COMMIT_SOURCE" ] && [ -z "$(cat "$COMMIT_MSG_FILE")" ]; then
    "%s" > "$COMMIT_MSG_FILE" 2>&1 || {
        echo "# cgpd failed to generate commit message" > "$COMMIT_MSG_FILE"
        exit 1
    }
fi
`, cgpdPath)
	}

	return fmt.Sprintf(`#!/bin/sh
# Auto-generated by cgpd
# This hook automatically generates commit messages using cgpd

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2

# Only run if no commit message provided (not amend, merge, etc.)
if [ -z "$COMMIT_SOURCE" ] && [ -z "$(cat "$COMMIT_MSG_FILE")" ]; then
    %s > "$COMMIT_MSG_FILE" 2>&1 || {
        echo "# cgpd failed to generate commit message" > "$COMMIT_MSG_FILE"
        exit 1
    }
fi
`, cgpdPath)
}

func installHooks(cmd *cobra.Command, args []string) error {
	gitDir, err := getGitRoot()
	if err != nil {
		return err
	}

	hooksDir := filepath.Join(gitDir, "hooks")
	hookPath := filepath.Join(hooksDir, "prepare-commit-msg")

	// Check if hook already exists
	if _, err := os.Stat(hookPath); err == nil {
		content, err := os.ReadFile(hookPath)
		if err == nil && strings.Contains(string(content), "Auto-generated by cgpd") {
			fmt.Fprintln(cmd.OutOrStdout(), "✓ cgpd hook is already installed")
			return nil
		}
		return fmt.Errorf("hook already exists at %s\nPlease remove it manually or use 'cgpd hooks uninstall --force'", hookPath)
	}

	// Create hooks directory if it doesn't exist
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return fmt.Errorf("create hooks directory: %w", err)
	}

	// Get cgpd path
	cgpdPath, err := getCgpdPath()
	if err != nil {
		return err
	}

	// Generate hook script
	script := generateHookScript(cgpdPath)

	// Write hook file
	if err := os.WriteFile(hookPath, []byte(script), 0o755); err != nil {
		return fmt.Errorf("write hook file: %w", err)
	}

	fmt.Fprintf(cmd.OutOrStdout(), "✓ Installed prepare-commit-msg hook\n")
	fmt.Fprintf(cmd.OutOrStdout(), "  Location: %s\n", hookPath)
	fmt.Fprintf(cmd.OutOrStdout(), "  cgpd path: %s\n", cgpdPath)
	fmt.Fprintln(cmd.OutOrStdout(), "\nCommit messages will now be automatically generated when you run 'git commit' without -m flag.")

	return nil
}

func uninstallHooks(cmd *cobra.Command, args []string) error {
	gitDir, err := getGitRoot()
	if err != nil {
		return err
	}

	hookPath := filepath.Join(gitDir, "hooks", "prepare-commit-msg")

	// Check if hook exists
	if _, err := os.Stat(hookPath); os.IsNotExist(err) {
		fmt.Fprintln(cmd.OutOrStdout(), "✓ No cgpd hook installed")
		return nil
	}

	// Read hook content to verify it's ours
	content, err := os.ReadFile(hookPath)
	if err != nil {
		return fmt.Errorf("read hook file: %w", err)
	}

	if !strings.Contains(string(content), "Auto-generated by cgpd") {
		return fmt.Errorf("hook exists but was not created by cgpd\nLocation: %s\nPlease remove it manually", hookPath)
	}

	// Remove hook
	if err := os.Remove(hookPath); err != nil {
		return fmt.Errorf("remove hook: %w", err)
	}

	fmt.Fprintf(cmd.OutOrStdout(), "✓ Uninstalled prepare-commit-msg hook\n")
	fmt.Fprintf(cmd.OutOrStdout(), "  Removed: %s\n", hookPath)

	return nil
}

func listHooks(cmd *cobra.Command, args []string) error {
	gitDir, err := getGitRoot()
	if err != nil {
		return err
	}

	hookPath := filepath.Join(gitDir, "hooks", "prepare-commit-msg")

	// Check if hook exists
	if _, err := os.Stat(hookPath); os.IsNotExist(err) {
		fmt.Fprintln(cmd.OutOrStdout(), "Status: Not installed")
		fmt.Fprintln(cmd.OutOrStdout(), "\nTo install, run: cgpd hooks install")
		return nil
	}

	// Read hook content
	content, err := os.ReadFile(hookPath)
	if err != nil {
		return fmt.Errorf("read hook file: %w", err)
	}

	isCgpdHook := strings.Contains(string(content), "Auto-generated by cgpd")

	if isCgpdHook {
		fmt.Fprintln(cmd.OutOrStdout(), "Status: ✓ Installed")
		fmt.Fprintf(cmd.OutOrStdout(), "Location: %s\n", hookPath)

		// Extract cgpd path from hook
		lines := strings.Split(string(content), "\n")
		for _, line := range lines {
			if strings.Contains(line, "cgpd") && !strings.HasPrefix(strings.TrimSpace(line), "#") {
				fmt.Fprintf(cmd.OutOrStdout(), "Hook calls: %s\n", strings.TrimSpace(line))
				break
			}
		}

		fmt.Fprintln(cmd.OutOrStdout(), "\nThe hook will automatically generate commit messages when you run:")
		fmt.Fprintln(cmd.OutOrStdout(), "  git commit  (without -m flag)")
	} else {
		fmt.Fprintln(cmd.OutOrStdout(), "Status: ⚠ Custom hook detected")
		fmt.Fprintf(cmd.OutOrStdout(), "Location: %s\n", hookPath)
		fmt.Fprintln(cmd.OutOrStdout(), "\nA prepare-commit-msg hook exists but was not created by cgpd.")
		fmt.Fprintln(cmd.OutOrStdout(), "To replace it, remove the existing hook first:")
		fmt.Fprintln(cmd.OutOrStdout(), "  rm", hookPath)
		fmt.Fprintln(cmd.OutOrStdout(), "Then run: cgpd hooks install")
	}

	return nil
}
