package cmd

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"github.com/spf13/cobra"
)

var hooksCmd = &cobra.Command{
	Use:   "hooks",
	Short: "Manage Git hooks integration",
	Long:  `Install, uninstall, or list Git hooks for automatic commit message generation.`,
}

var (
	flagHookForce bool
	flagHookChain bool
)

var installHookCmd = &cobra.Command{
	Use:   "install",
	Short: "Install Git hooks",
	Long: `Install prepare-commit-msg hook to automatically generate commit messages.
The hook will run cgpd when no commit message is provided.

By default, cgpd will refuse to overwrite an existing hook.
Use --chain to preserve the existing hook and run cgpd after it.
Use --force to replace the existing hook (a backup will be created).`,
	RunE: installHooks,
}

var uninstallHookCmd = &cobra.Command{
	Use:   "uninstall",
	Short: "Uninstall Git hooks",
	Long:  `Remove the installed prepare-commit-msg hook.`,
	RunE:  uninstallHooks,
}

var listHookCmd = &cobra.Command{
	Use:   "list",
	Short: "List installed hooks",
	Long:  `Show the status of cgpd Git hooks.`,
	RunE:  listHooks,
}

var (
	flagPreCommitForce bool
	flagPreCommitChain bool
	flagCommitMsgForce bool
	flagCommitMsgChain bool
)

var preCommitCmd = &cobra.Command{
	Use:   "pre-commit",
	Short: "Manage pre-commit hook (security scan)",
	Long:  `Install, uninstall, or list pre-commit hook to block commits containing sensitive files or secrets.`,
}

var preCommitInstallCmd = &cobra.Command{
	Use:   "install",
	Short: "Install pre-commit hook",
	RunE:  installPreCommitHook,
}

var preCommitUninstallCmd = &cobra.Command{
	Use:   "uninstall",
	Short: "Uninstall pre-commit hook",
	RunE:  uninstallPreCommitHook,
}

var preCommitListCmd = &cobra.Command{
	Use:   "list",
	Short: "List pre-commit hook status",
	RunE:  listPreCommitHook,
}

var commitMsgCmd = &cobra.Command{
	Use:   "commit-msg",
	Short: "Manage commit-msg hook (message validation)",
	Long:  `Install, uninstall, or list commit-msg hook to validate the commit subject line.`,
}

var commitMsgInstallCmd = &cobra.Command{
	Use:   "install",
	Short: "Install commit-msg hook",
	RunE:  installCommitMsgHook,
}

var commitMsgUninstallCmd = &cobra.Command{
	Use:   "uninstall",
	Short: "Uninstall commit-msg hook",
	RunE:  uninstallCommitMsgHook,
}

var commitMsgListCmd = &cobra.Command{
	Use:   "list",
	Short: "List commit-msg hook status",
	RunE:  listCommitMsgHook,
}

func init() {
	rootCmd.AddCommand(hooksCmd)
	hooksCmd.AddCommand(installHookCmd)
	hooksCmd.AddCommand(uninstallHookCmd)
	hooksCmd.AddCommand(listHookCmd)

	hooksCmd.AddCommand(preCommitCmd)
	preCommitCmd.AddCommand(preCommitInstallCmd)
	preCommitCmd.AddCommand(preCommitUninstallCmd)
	preCommitCmd.AddCommand(preCommitListCmd)

	hooksCmd.AddCommand(commitMsgCmd)
	commitMsgCmd.AddCommand(commitMsgInstallCmd)
	commitMsgCmd.AddCommand(commitMsgUninstallCmd)
	commitMsgCmd.AddCommand(commitMsgListCmd)

	installHookCmd.Flags().BoolVar(&flagHookChain, "chain", false, "Preserve existing hook and run cgpd after it")
	installHookCmd.Flags().BoolVar(&flagHookForce, "force", false, "Replace existing hook (creates a backup)")

	preCommitInstallCmd.Flags().BoolVar(&flagPreCommitChain, "chain", false, "Preserve existing hook and run cgpd after it")
	preCommitInstallCmd.Flags().BoolVar(&flagPreCommitForce, "force", false, "Replace existing hook (creates a backup)")

	commitMsgInstallCmd.Flags().BoolVar(&flagCommitMsgChain, "chain", false, "Preserve existing hook and run cgpd validations after it")
	commitMsgInstallCmd.Flags().BoolVar(&flagCommitMsgForce, "force", false, "Replace existing hook (creates a backup)")
}

func getGitRoot() (string, error) {
	cmd := exec.Command("git", "rev-parse", "--git-dir")
	out, err := cmd.Output()
	if err != nil {
		return "", errors.New("not a git repository")
	}
	gitDir := strings.TrimSpace(string(out))
	if !filepath.IsAbs(gitDir) {
		wd, err := os.Getwd()
		if err != nil {
			return "", err
		}
		gitDir = filepath.Join(wd, gitDir)
	}
	return gitDir, nil
}

func getCgpdPath() (string, error) {
	// Try to find cgpd in PATH
	path, err := exec.LookPath("cgpd")
	if err == nil {
		return path, nil
	}

	// Fallback to current executable
	exe, err := os.Executable()
	if err != nil {
		return "", fmt.Errorf("cannot determine cgpd location: %w", err)
	}
	return exe, nil
}

const (
	hookFileName          = "prepare-commit-msg"
	preCommitHookFileName = "pre-commit"
	commitMsgHookFileName = "commit-msg"

	cgpdHookMarker      = "Auto-generated by cgpd"
	cgpdHookModeLineKey = "cgpd-hook-mode:"
	cgpdHookModeChained = "chained"
	cgpdHookModeSingle  = "standalone"

	cgpdUserHookSuffix   = ".cgpd-user"
	cgpdBackupSuffixPref = ".cgpd-backup-"
)

func shellQuote(s string) string {
	if s == "" {
		return "''"
	}
	return "'" + strings.ReplaceAll(s, "'", "'\"'\"'") + "'"
}

func generateHookScript(cgpdPath string, chainedHookPath string) string {
	mode := cgpdHookModeSingle
	if strings.TrimSpace(chainedHookPath) != "" {
		mode = cgpdHookModeChained
	}

	return fmt.Sprintf(`#!/bin/sh
# %s
# cgpd-hook: %s
# %s %s

CGPD_BIN=%s
CHAINED_HOOK=%s

COMMIT_MSG_FILE=$1
COMMIT_SOURCE=$2

# If chaining is enabled, run the user's existing hook first.
if [ -n "$CHAINED_HOOK" ] && [ -x "$CHAINED_HOOK" ]; then
    "$CHAINED_HOOK" "$@"
    status=$?
    if [ $status -ne 0 ]; then
        exit $status
    fi
fi

# Only run if no commit message provided (not amend, merge, etc.)
if [ -z "$COMMIT_SOURCE" ] && [ -z "$(cat "$COMMIT_MSG_FILE" 2>/dev/null)" ]; then
    CGPD_NO_SPINNER=1 CGPD_NON_INTERACTIVE=1 "$CGPD_BIN" > "$COMMIT_MSG_FILE" || {
        echo "# cgpd failed to generate commit message" > "$COMMIT_MSG_FILE"
        exit 1
    }
fi
`, cgpdHookMarker, hookFileName, cgpdHookModeLineKey, mode, shellQuote(cgpdPath), shellQuote(chainedHookPath))
}

func generatePreCommitHookScript(cgpdPath string, chainedHookPath string) string {
	mode := cgpdHookModeSingle
	if strings.TrimSpace(chainedHookPath) != "" {
		mode = cgpdHookModeChained
	}

	return fmt.Sprintf(`#!/bin/sh
# %s
# cgpd-hook: %s
# %s %s

CGPD_BIN=%s
CHAINED_HOOK=%s

if [ -n "$CHAINED_HOOK" ] && [ -x "$CHAINED_HOOK" ]; then
    "$CHAINED_HOOK" "$@"
    status=$?
    if [ $status -ne 0 ]; then
        exit $status
    fi
fi

CGPD_NO_SPINNER=1 CGPD_NON_INTERACTIVE=1 "$CGPD_BIN" security scan --diff
`, cgpdHookMarker, preCommitHookFileName, cgpdHookModeLineKey, mode, shellQuote(cgpdPath), shellQuote(chainedHookPath))
}

func generateCommitMsgHookScript(chainedHookPath string) string {
	mode := cgpdHookModeSingle
	if strings.TrimSpace(chainedHookPath) != "" {
		mode = cgpdHookModeChained
	}

	return fmt.Sprintf(`#!/bin/sh
# %s
# cgpd-hook: %s
# %s %s

CHAINED_HOOK=%s

if [ -n "$CHAINED_HOOK" ] && [ -x "$CHAINED_HOOK" ]; then
    "$CHAINED_HOOK" "$@"
    status=$?
    if [ $status -ne 0 ]; then
        exit $status
    fi
fi

COMMIT_MSG_FILE=$1
IFS= read -r subject < "$COMMIT_MSG_FILE"

if [ -z "$subject" ]; then
    echo "cgpd: empty commit message" 1>&2
    exit 1
fi

len=${#subject}
if [ $len -gt 72 ]; then
    echo "cgpd: commit subject too long ($len > 72)" 1>&2
    exit 1
fi
`, cgpdHookMarker, commitMsgHookFileName, cgpdHookModeLineKey, mode, shellQuote(chainedHookPath))
}

func installHooks(cmd *cobra.Command, args []string) error {
	gitDir, err := getGitRoot()
	if err != nil {
		return err
	}

	if flagHookForce && flagHookChain {
		return errors.New("cannot use --force and --chain together")
	}

	hooksDir := filepath.Join(gitDir, "hooks")
	hookPath := filepath.Join(hooksDir, hookFileName)
	userHookPath := hookPath + cgpdUserHookSuffix

	// Create hooks directory if it doesn't exist
	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return fmt.Errorf("create hooks directory: %w", err)
	}

	var chainedHookPath string

	if _, err := os.Stat(hookPath); err == nil {
		content, readErr := os.ReadFile(hookPath)
		if readErr == nil && strings.Contains(string(content), cgpdHookMarker) {
			fmt.Fprintln(cmd.OutOrStdout(), "✓ cgpd hook is already installed")
			return nil
		}

		switch {
		case flagHookChain:
			if _, err := os.Stat(userHookPath); err == nil {
				return fmt.Errorf("cannot chain install: %s already exists", userHookPath)
			}
			if err := os.Rename(hookPath, userHookPath); err != nil {
				return fmt.Errorf("preserve existing hook: %w", err)
			}
			chainedHookPath = userHookPath
		case flagHookForce:
			backupPath := hookPath + cgpdBackupSuffixPref + time.Now().Format("20060102-150405")
			if err := os.Rename(hookPath, backupPath); err != nil {
				return fmt.Errorf("backup existing hook: %w", err)
			}
		default:
			return fmt.Errorf("hook already exists at %s\nUse 'cgpd hooks install --chain' to preserve it, or '--force' to replace it", hookPath)
		}
	}

	cgpdPath, err := getCgpdPath()
	if err != nil {
		return err
	}

	script := generateHookScript(cgpdPath, chainedHookPath)
	if err := os.WriteFile(hookPath, []byte(script), 0o755); err != nil {
		return fmt.Errorf("write hook file: %w", err)
	}

	fmt.Fprintf(cmd.OutOrStdout(), "✓ Installed %s hook\n", hookFileName)
	fmt.Fprintf(cmd.OutOrStdout(), "  Location: %s\n", hookPath)
	fmt.Fprintf(cmd.OutOrStdout(), "  cgpd path: %s\n", cgpdPath)
	if chainedHookPath != "" {
		fmt.Fprintf(cmd.OutOrStdout(), "  Mode: chained (%s)\n", chainedHookPath)
	} else {
		fmt.Fprintln(cmd.OutOrStdout(), "  Mode: standalone")
	}
	fmt.Fprintln(cmd.OutOrStdout(), "\nCommit messages will now be automatically generated when you run 'git commit' without -m flag.")

	return nil
}

func uninstallHooks(cmd *cobra.Command, args []string) error {
	gitDir, err := getGitRoot()
	if err != nil {
		return err
	}

	hooksDir := filepath.Join(gitDir, "hooks")
	hookPath := filepath.Join(hooksDir, hookFileName)
	userHookPath := hookPath + cgpdUserHookSuffix

	if _, err := os.Stat(hookPath); os.IsNotExist(err) {
		fmt.Fprintln(cmd.OutOrStdout(), "✓ No cgpd hook installed")
		return nil
	}

	content, err := os.ReadFile(hookPath)
	if err != nil {
		return fmt.Errorf("read hook file: %w", err)
	}
	if !strings.Contains(string(content), cgpdHookMarker) {
		return fmt.Errorf("hook exists but was not created by cgpd\nLocation: %s\nPlease remove it manually", hookPath)
	}

	isChained := strings.Contains(string(content), cgpdHookModeLineKey+" "+cgpdHookModeChained)

	if err := os.Remove(hookPath); err != nil {
		return fmt.Errorf("remove hook: %w", err)
	}

	if isChained {
		if _, err := os.Stat(userHookPath); err == nil {
			if err := os.Rename(userHookPath, hookPath); err != nil {
				return fmt.Errorf("restore previous hook: %w", err)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "✓ Uninstalled cgpd hook and restored previous %s hook\n", hookFileName)
			fmt.Fprintf(cmd.OutOrStdout(), "  Restored: %s\n", hookPath)
			return nil
		}
	}

	fmt.Fprintf(cmd.OutOrStdout(), "✓ Uninstalled %s hook\n", hookFileName)
	fmt.Fprintf(cmd.OutOrStdout(), "  Removed: %s\n", hookPath)

	return nil
}

func listHooks(cmd *cobra.Command, args []string) error {
	gitDir, err := getGitRoot()
	if err != nil {
		return err
	}

	hooksDir := filepath.Join(gitDir, "hooks")
	hookPath := filepath.Join(hooksDir, hookFileName)
	userHookPath := hookPath + cgpdUserHookSuffix

	if _, err := os.Stat(hookPath); os.IsNotExist(err) {
		fmt.Fprintln(cmd.OutOrStdout(), "Status: Not installed")
		fmt.Fprintln(cmd.OutOrStdout(), "\nTo install, run: cgpd hooks install")
		return nil
	}

	content, err := os.ReadFile(hookPath)
	if err != nil {
		return fmt.Errorf("read hook file: %w", err)
	}

	isCgpdHook := strings.Contains(string(content), cgpdHookMarker)
	if !isCgpdHook {
		fmt.Fprintln(cmd.OutOrStdout(), "Status: ⚠ Custom hook detected")
		fmt.Fprintf(cmd.OutOrStdout(), "Location: %s\n", hookPath)
		fmt.Fprintf(cmd.OutOrStdout(), "\nA %s hook exists but was not created by cgpd.\n", hookFileName)
		fmt.Fprintln(cmd.OutOrStdout(), "To replace it:")
		fmt.Fprintln(cmd.OutOrStdout(), "  cgpd hooks install --chain")
		fmt.Fprintln(cmd.OutOrStdout(), "or:")
		fmt.Fprintln(cmd.OutOrStdout(), "  cgpd hooks install --force")
		return nil
	}

	mode := cgpdHookModeSingle
	if strings.Contains(string(content), cgpdHookModeLineKey+" "+cgpdHookModeChained) {
		mode = cgpdHookModeChained
	}

	fmt.Fprintln(cmd.OutOrStdout(), "Status: ✓ Installed (cgpd)")
	fmt.Fprintf(cmd.OutOrStdout(), "Location: %s\n", hookPath)
	fmt.Fprintf(cmd.OutOrStdout(), "Mode: %s\n", mode)

	if mode == cgpdHookModeChained {
		if _, err := os.Stat(userHookPath); err == nil {
			fmt.Fprintf(cmd.OutOrStdout(), "Chained hook: %s\n", userHookPath)
		}
	}

	fmt.Fprintln(cmd.OutOrStdout(), "\nThe hook will automatically generate commit messages when you run:")
	fmt.Fprintln(cmd.OutOrStdout(), "  git commit  (without -m flag)")
	return nil
}

func installPreCommitHook(cmd *cobra.Command, args []string) error {
	gitDir, err := getGitRoot()
	if err != nil {
		return err
	}

	if flagPreCommitForce && flagPreCommitChain {
		return errors.New("cannot use --force and --chain together")
	}

	hooksDir := filepath.Join(gitDir, "hooks")
	hookPath := filepath.Join(hooksDir, preCommitHookFileName)
	userHookPath := hookPath + cgpdUserHookSuffix

	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return fmt.Errorf("create hooks directory: %w", err)
	}

	var chainedHookPath string
	if _, err := os.Stat(hookPath); err == nil {
		content, readErr := os.ReadFile(hookPath)
		if readErr == nil && strings.Contains(string(content), cgpdHookMarker) {
			fmt.Fprintln(cmd.OutOrStdout(), "✓ cgpd hook is already installed")
			return nil
		}

		switch {
		case flagPreCommitChain:
			if _, err := os.Stat(userHookPath); err == nil {
				return fmt.Errorf("cannot chain install: %s already exists", userHookPath)
			}
			if err := os.Rename(hookPath, userHookPath); err != nil {
				return fmt.Errorf("preserve existing hook: %w", err)
			}
			chainedHookPath = userHookPath
		case flagPreCommitForce:
			backupPath := hookPath + cgpdBackupSuffixPref + time.Now().Format("20060102-150405")
			if err := os.Rename(hookPath, backupPath); err != nil {
				return fmt.Errorf("backup existing hook: %w", err)
			}
		default:
			return fmt.Errorf("hook already exists at %s\nUse 'cgpd hooks pre-commit install --chain' to preserve it, or '--force' to replace it", hookPath)
		}
	}

	cgpdPath, err := getCgpdPath()
	if err != nil {
		return err
	}

	script := generatePreCommitHookScript(cgpdPath, chainedHookPath)
	if err := os.WriteFile(hookPath, []byte(script), 0o755); err != nil {
		return fmt.Errorf("write hook file: %w", err)
	}

	fmt.Fprintf(cmd.OutOrStdout(), "✓ Installed %s hook\n", preCommitHookFileName)
	fmt.Fprintf(cmd.OutOrStdout(), "  Location: %s\n", hookPath)
	fmt.Fprintf(cmd.OutOrStdout(), "  cgpd path: %s\n", cgpdPath)
	if chainedHookPath != "" {
		fmt.Fprintf(cmd.OutOrStdout(), "  Mode: chained (%s)\n", chainedHookPath)
	} else {
		fmt.Fprintln(cmd.OutOrStdout(), "  Mode: standalone")
	}
	fmt.Fprintln(cmd.OutOrStdout(), "\nCommits will be blocked if sensitive files or potential secrets are detected.")
	return nil
}

func uninstallPreCommitHook(cmd *cobra.Command, args []string) error {
	gitDir, err := getGitRoot()
	if err != nil {
		return err
	}

	hooksDir := filepath.Join(gitDir, "hooks")
	hookPath := filepath.Join(hooksDir, preCommitHookFileName)
	userHookPath := hookPath + cgpdUserHookSuffix

	if _, err := os.Stat(hookPath); os.IsNotExist(err) {
		fmt.Fprintln(cmd.OutOrStdout(), "✓ No cgpd hook installed")
		return nil
	}

	content, err := os.ReadFile(hookPath)
	if err != nil {
		return fmt.Errorf("read hook file: %w", err)
	}
	if !strings.Contains(string(content), cgpdHookMarker) {
		return fmt.Errorf("hook exists but was not created by cgpd\nLocation: %s\nPlease remove it manually", hookPath)
	}

	isChained := strings.Contains(string(content), cgpdHookModeLineKey+" "+cgpdHookModeChained)
	if err := os.Remove(hookPath); err != nil {
		return fmt.Errorf("remove hook: %w", err)
	}

	if isChained {
		if _, err := os.Stat(userHookPath); err == nil {
			if err := os.Rename(userHookPath, hookPath); err != nil {
				return fmt.Errorf("restore previous hook: %w", err)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "✓ Uninstalled cgpd hook and restored previous %s hook\n", preCommitHookFileName)
			fmt.Fprintf(cmd.OutOrStdout(), "  Restored: %s\n", hookPath)
			return nil
		}
	}

	fmt.Fprintf(cmd.OutOrStdout(), "✓ Uninstalled %s hook\n", preCommitHookFileName)
	fmt.Fprintf(cmd.OutOrStdout(), "  Removed: %s\n", hookPath)
	return nil
}

func listPreCommitHook(cmd *cobra.Command, args []string) error {
	gitDir, err := getGitRoot()
	if err != nil {
		return err
	}

	hooksDir := filepath.Join(gitDir, "hooks")
	hookPath := filepath.Join(hooksDir, preCommitHookFileName)
	userHookPath := hookPath + cgpdUserHookSuffix

	if _, err := os.Stat(hookPath); os.IsNotExist(err) {
		fmt.Fprintln(cmd.OutOrStdout(), "Status: Not installed")
		fmt.Fprintln(cmd.OutOrStdout(), "\nTo install, run: cgpd hooks pre-commit install")
		return nil
	}

	content, err := os.ReadFile(hookPath)
	if err != nil {
		return fmt.Errorf("read hook file: %w", err)
	}

	isCgpdHook := strings.Contains(string(content), cgpdHookMarker)
	if !isCgpdHook {
		fmt.Fprintln(cmd.OutOrStdout(), "Status: ⚠ Custom hook detected")
		fmt.Fprintf(cmd.OutOrStdout(), "Location: %s\n", hookPath)
		fmt.Fprintf(cmd.OutOrStdout(), "\nA %s hook exists but was not created by cgpd.\n", preCommitHookFileName)
		fmt.Fprintln(cmd.OutOrStdout(), "To replace it:")
		fmt.Fprintln(cmd.OutOrStdout(), "  cgpd hooks pre-commit install --chain")
		fmt.Fprintln(cmd.OutOrStdout(), "or:")
		fmt.Fprintln(cmd.OutOrStdout(), "  cgpd hooks pre-commit install --force")
		return nil
	}

	mode := cgpdHookModeSingle
	if strings.Contains(string(content), cgpdHookModeLineKey+" "+cgpdHookModeChained) {
		mode = cgpdHookModeChained
	}

	fmt.Fprintln(cmd.OutOrStdout(), "Status: ✓ Installed (cgpd)")
	fmt.Fprintf(cmd.OutOrStdout(), "Location: %s\n", hookPath)
	fmt.Fprintf(cmd.OutOrStdout(), "Mode: %s\n", mode)
	if mode == cgpdHookModeChained {
		if _, err := os.Stat(userHookPath); err == nil {
			fmt.Fprintf(cmd.OutOrStdout(), "Chained hook: %s\n", userHookPath)
		}
	}
	return nil
}

func installCommitMsgHook(cmd *cobra.Command, args []string) error {
	gitDir, err := getGitRoot()
	if err != nil {
		return err
	}

	if flagCommitMsgForce && flagCommitMsgChain {
		return errors.New("cannot use --force and --chain together")
	}

	hooksDir := filepath.Join(gitDir, "hooks")
	hookPath := filepath.Join(hooksDir, commitMsgHookFileName)
	userHookPath := hookPath + cgpdUserHookSuffix

	if err := os.MkdirAll(hooksDir, 0o755); err != nil {
		return fmt.Errorf("create hooks directory: %w", err)
	}

	var chainedHookPath string
	if _, err := os.Stat(hookPath); err == nil {
		content, readErr := os.ReadFile(hookPath)
		if readErr == nil && strings.Contains(string(content), cgpdHookMarker) {
			fmt.Fprintln(cmd.OutOrStdout(), "✓ cgpd hook is already installed")
			return nil
		}

		switch {
		case flagCommitMsgChain:
			if _, err := os.Stat(userHookPath); err == nil {
				return fmt.Errorf("cannot chain install: %s already exists", userHookPath)
			}
			if err := os.Rename(hookPath, userHookPath); err != nil {
				return fmt.Errorf("preserve existing hook: %w", err)
			}
			chainedHookPath = userHookPath
		case flagCommitMsgForce:
			backupPath := hookPath + cgpdBackupSuffixPref + time.Now().Format("20060102-150405")
			if err := os.Rename(hookPath, backupPath); err != nil {
				return fmt.Errorf("backup existing hook: %w", err)
			}
		default:
			return fmt.Errorf("hook already exists at %s\nUse 'cgpd hooks commit-msg install --chain' to preserve it, or '--force' to replace it", hookPath)
		}
	}

	script := generateCommitMsgHookScript(chainedHookPath)
	if err := os.WriteFile(hookPath, []byte(script), 0o755); err != nil {
		return fmt.Errorf("write hook file: %w", err)
	}

	fmt.Fprintf(cmd.OutOrStdout(), "✓ Installed %s hook\n", commitMsgHookFileName)
	fmt.Fprintf(cmd.OutOrStdout(), "  Location: %s\n", hookPath)
	if chainedHookPath != "" {
		fmt.Fprintf(cmd.OutOrStdout(), "  Mode: chained (%s)\n", chainedHookPath)
	} else {
		fmt.Fprintln(cmd.OutOrStdout(), "  Mode: standalone")
	}
	fmt.Fprintln(cmd.OutOrStdout(), "\nCommit will be blocked if the subject line is empty or exceeds 72 characters.")
	return nil
}

func uninstallCommitMsgHook(cmd *cobra.Command, args []string) error {
	gitDir, err := getGitRoot()
	if err != nil {
		return err
	}

	hooksDir := filepath.Join(gitDir, "hooks")
	hookPath := filepath.Join(hooksDir, commitMsgHookFileName)
	userHookPath := hookPath + cgpdUserHookSuffix

	if _, err := os.Stat(hookPath); os.IsNotExist(err) {
		fmt.Fprintln(cmd.OutOrStdout(), "✓ No cgpd hook installed")
		return nil
	}

	content, err := os.ReadFile(hookPath)
	if err != nil {
		return fmt.Errorf("read hook file: %w", err)
	}
	if !strings.Contains(string(content), cgpdHookMarker) {
		return fmt.Errorf("hook exists but was not created by cgpd\nLocation: %s\nPlease remove it manually", hookPath)
	}

	isChained := strings.Contains(string(content), cgpdHookModeLineKey+" "+cgpdHookModeChained)
	if err := os.Remove(hookPath); err != nil {
		return fmt.Errorf("remove hook: %w", err)
	}

	if isChained {
		if _, err := os.Stat(userHookPath); err == nil {
			if err := os.Rename(userHookPath, hookPath); err != nil {
				return fmt.Errorf("restore previous hook: %w", err)
			}
			fmt.Fprintf(cmd.OutOrStdout(), "✓ Uninstalled cgpd hook and restored previous %s hook\n", commitMsgHookFileName)
			fmt.Fprintf(cmd.OutOrStdout(), "  Restored: %s\n", hookPath)
			return nil
		}
	}

	fmt.Fprintf(cmd.OutOrStdout(), "✓ Uninstalled %s hook\n", commitMsgHookFileName)
	fmt.Fprintf(cmd.OutOrStdout(), "  Removed: %s\n", hookPath)
	return nil
}

func listCommitMsgHook(cmd *cobra.Command, args []string) error {
	gitDir, err := getGitRoot()
	if err != nil {
		return err
	}

	hooksDir := filepath.Join(gitDir, "hooks")
	hookPath := filepath.Join(hooksDir, commitMsgHookFileName)
	userHookPath := hookPath + cgpdUserHookSuffix

	if _, err := os.Stat(hookPath); os.IsNotExist(err) {
		fmt.Fprintln(cmd.OutOrStdout(), "Status: Not installed")
		fmt.Fprintln(cmd.OutOrStdout(), "\nTo install, run: cgpd hooks commit-msg install")
		return nil
	}

	content, err := os.ReadFile(hookPath)
	if err != nil {
		return fmt.Errorf("read hook file: %w", err)
	}

	isCgpdHook := strings.Contains(string(content), cgpdHookMarker)
	if !isCgpdHook {
		fmt.Fprintln(cmd.OutOrStdout(), "Status: ⚠ Custom hook detected")
		fmt.Fprintf(cmd.OutOrStdout(), "Location: %s\n", hookPath)
		fmt.Fprintf(cmd.OutOrStdout(), "\nA %s hook exists but was not created by cgpd.\n", commitMsgHookFileName)
		fmt.Fprintln(cmd.OutOrStdout(), "To replace it:")
		fmt.Fprintln(cmd.OutOrStdout(), "  cgpd hooks commit-msg install --chain")
		fmt.Fprintln(cmd.OutOrStdout(), "or:")
		fmt.Fprintln(cmd.OutOrStdout(), "  cgpd hooks commit-msg install --force")
		return nil
	}

	mode := cgpdHookModeSingle
	if strings.Contains(string(content), cgpdHookModeLineKey+" "+cgpdHookModeChained) {
		mode = cgpdHookModeChained
	}

	fmt.Fprintln(cmd.OutOrStdout(), "Status: ✓ Installed (cgpd)")
	fmt.Fprintf(cmd.OutOrStdout(), "Location: %s\n", hookPath)
	fmt.Fprintf(cmd.OutOrStdout(), "Mode: %s\n", mode)
	if mode == cgpdHookModeChained {
		if _, err := os.Stat(userHookPath); err == nil {
			fmt.Fprintf(cmd.OutOrStdout(), "Chained hook: %s\n", userHookPath)
		}
	}
	return nil
}
